_target_: sn_gamestate.calibration.postprocess_calib.CalibrationRefiner
image_width: 1920
image_height: 1080
outlier_model_path: "/Users/jeangrifnee/PycharmProjects/soccernet/evalCalibration/calib_clf.pkl"